[theme]
base="light"
primaryColor="#0072CE"
backgroundColor="#ffffff"
secondaryBackgroundColor="#e8eef9"
textColor="#011000"
font="sans serif"
[server]
enableWebsocketCompression=false
enableCORS=false

