server.enableWebsocketCompression=false
server.enableCORS=false
base="light"
primaryColor="#0072CE"
backgroundColor="#ffffff"
secondaryBackgroundColor="#e8eef9"
textColor="#110111"
font="sans serif"

